spring:
  datasource:
    url: jdbc:mysql://rm-bp13o1q3llu8vn5z6lo.mysql.rds.aliyuncs.com:3306/tenement_zuzu
    username: adminroot
    password: xyza123!@#
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 3000
      initial-size: 10
      max-idle: 60
      min-idle: 10
      max-active: 80
      time-between-eviction-runs-millis: 3600000
      test-on-borrow: false
      min-evictable-idle-time-millis: 1800000
      num-tests-per-eviction-run: 3
      connection-properties: useUnicode=true;characterEncoding=utf-8;
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100000
weapp:
  appid:
  secret:

qqmap:
  key: 7I3BZ-TZKCP-HWQDI-VM5ZZ-5FBG5-4ZBX4


