server:
  port: 10007
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellochenyao/spring-cloud-config.git
          username: hellochenyao
          password: a1314520AA
          default-label: master
          search-paths: config
eureka:
  client:
    serviceUrl:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    preferIpAddress: true